service: persona

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: api/persona.guardar
    description: Guardar la informacion de una persona.
    events:
      - http: 
          path: personas
          method: post
